global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: cockroachdb
    honor_timestamps: true
    metrics_path: /_status/vars
    scheme: http
    static_configs:
      - targets:
          - localhost:8080
  - job_name: backend
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - docker.for.mac.localhost:3000