{
 "title": "inet_tcp_metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "src_node",
    "label": "Source node",
    "query": "label_values(inet_tcp_metrics_packet_size_bytes_sum, src_node)"
   },
   {
    "name": "dst_node",
    "label": "Destination node",
    "query": "label_values(inet_tcp_metrics_packet_size_bytes_sum{src_node=\"$src_node\"}, dst_node)"
   },
   {
    "name": "traffic_direction",
    "label": "Traffic direction",
    "query": "label_values(inet_tcp_metrics_packet_size_bytes_sum, traffic_direction)"
   },
   { "name": "time_interval", "label": "Time interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(rabbitmq_build_info * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_node=~\"$src_node|$dst_node\"}) by(erlang_version, rabbitmq_version, product_version, prometheus_client_version, rabbitmq_node, rabbitmq_cluster)"
    }
   ]
  },
  {
   "title": "$src_node $traffic_direction traffic from/to $dst_node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "repeat": "traffic_direction",
   "collapsed": true,
   "panels": [
    {
     "title": "Packets per second by size in bytes, measured over $time_interval",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_packet_size_bytes_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Packets by type per second, measured over $time_interval",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_packet_type_total{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{packet_type}}"
      }
     ]
    },
    {
     "title": "Fragmented messages per second by fragments, measured over $time_interval",
     "type": "heatmap",
     "description": "Messages larger than 64KB will be split into multiple fragments. This functionality was introduced in OTP-22 so that smaller messages can be interleaved between larges messages.\n\nWhen distribution runs in debug mode, messages larger than 1KB will be split into multiple fragments.\n\n* [Distribution Header for fragmented messages](http://erlang.org/doc/apps/erts/erl_ext_dist.html#distribution-header-for-fragmented-messages)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_fragmented_messages_total_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Number of control messages per second, measured over $time_interval",
     "type": "graph",
     "description": "* [ControlMessage types](http://erlang.org/doc/apps/erts/erl_dist_protocol.html#control_message)",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_control_message_total{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{control_message}}"
      }
     ]
    },
    {
     "title": "New ATOM_CACHE_REF entries per second by entries, measured over $time_interval",
     "type": "bargauge",
     "description": "The distribution header is sent by the erlang distribution to carry metadata about the coming control message and potential payload. It is primarily used to handle the atom cache in the Erlang distribution. Since OTP-22 it is also used to fragment large distribution messages into multiple smaller fragments.\n\n* https://erlang.org/doc/apps/erts/erl_ext_dist.html#normal-distribution-header",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_atom_cache_ref_new_entries_total_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "New ATOM_CACHE_REF entries per second by entries, measured over $time_interval",
     "type": "heatmap",
     "description": "The distribution header is sent by the erlang distribution to carry metadata about the coming control message and potential payload. It is primarily used to handle the atom cache in the Erlang distribution. Since OTP-22 it is also used to fragment large distribution messages into multiple smaller fragments.\n\n* https://erlang.org/doc/apps/erts/erl_ext_dist.html#normal-distribution-header",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_atom_cache_ref_new_entries_total_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total ATOM_CACHE_REF entries per second by entries, measured over $time_interval",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_atom_cache_ref_entries_total_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total ATOM_CACHE_REF entries per second by entries, measured over $time_interval",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_atom_cache_ref_entries_total_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\", traffic_direction=\"$traffic_direction\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Function calls for receiving data (incoming traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets received from the socket by duration, measured over $time_interval",
     "type": "bargauge",
     "description": "* `1.0e-6` 1 microsecond\n* `1.0e-5` 10 microseconds\n* `0.0001` 100 microseconds\n* `0.001` 1 millisecond",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_receive_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Packets received from the socket by duration, measured over $time_interval",
     "type": "heatmap",
     "description": "Lowest value is in microsecond, highest is in milliseconds.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_receive_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Calls that enqueue packets into the VM by duration, measured over $time_interval",
     "type": "bargauge",
     "description": "* [erlang:dist_ctrl_put_data/2](https://erlang.org/doc/man/erlang.html#dist_ctrl_put_data-2)\n\nTime duration conversion\n* `1.0e-6` 1 microsecond\n* `1.0e-5` 10 microseconds\n* `0.0001` 100 microseconds\n* `0.001` 1 millisecond",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_dist_ctrl_put_data_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Calls that enqueue packets into the VM by duration, measured over $time_interval",
     "type": "heatmap",
     "description": "* [erlang:dist_ctrl_put_data/2](https://erlang.org/doc/man/erlang.html#dist_ctrl_put_data-2)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "rate(inet_tcp_metrics_dist_ctrl_put_data_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Function calls for sending data (outgoing traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Calls that get packets from the VM by duration, measured over $time_interval",
   "type": "bargauge",
   "description": "* [erlang:dist_ctrl_get_data/1](https://erlang.org/doc/man/erlang.html#dist_ctrl_get_data-1)\n\nTime duration conversion\n* `1.0e-6` 1 microsecond\n* `1.0e-5` 10 microseconds\n* `0.0001` 100 microseconds\n* `0.001` 1 millisecond",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(inet_tcp_metrics_dist_ctrl_get_data_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Calls that get packets from the VM by duration, measured over $time_interval",
   "type": "heatmap",
   "description": "* [erlang:dist_ctrl_get_data/1](https://erlang.org/doc/man/erlang.html#dist_ctrl_get_data-1)\n\nLowest value is in microseconds, highest is in milliseconds.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(inet_tcp_metrics_dist_ctrl_get_data_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Calls that send packets to the socket by duration, measured over $time_interval",
   "type": "bargauge",
   "description": "The equivalent of `gen_tcp:send/1`, but for Erlang Distribution.\n\nTime duration conversion\n* `1.0e-6` 1 microsecond\n* `1.0e-5` 10 microseconds\n* `0.0001` 100 microseconds\n* `0.001` 1 millisecond",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(inet_tcp_metrics_driver_send_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Calls that send packets to the socket by duration, measured over $time_interval",
   "type": "heatmap",
   "description": "The equivalent of `gen_tcp:send/1`, but for Erlang Distribution.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(inet_tcp_metrics_driver_send_duration_seconds_bucket{src_node=\"$src_node\", dst_node=\"$dst_node\"}[$time_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TODO",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "* Publish rabbitmq Docker image with inet_tcp_metrics\n* Publish dashboard to grafana.com\n* Write README\n* Share on the erlang-questions mailing list"
   },
   "content": "* Publish rabbitmq Docker image with inet_tcp_metrics\n* Publish dashboard to grafana.com\n* Write README\n* Share on the erlang-questions mailing list"
  }
 ]
}