global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: node-exporter
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: 
        - node-exporter:9100
  - job_name: postgres-exporter
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets: 
        - postgres-exporter:9187
  - job_name: alertmanager
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - alertmanager:9093
  - job_name: rabbitmq
    honor_timestamps: true
    metrics_path: /metrics
    static_configs:
      - targets:
        - rabbitmq:15692
